name = input("enter your name:")
last_name = input("enter your last name:")
age = input("what is your age:")
height = input("what is your height:")
year = input("what year where you born:")
print(name ,last_name,age,height,year)